export const OBRAS_SOCIALES_LIST = [
  'Acindar',
  'América Servicios',
  'AMFFA Salud',
  'AMR Salud',
  'Andar',
  'APSOT',
  'Assistravel',
  'Avalian',
  'Bassi',
  'Caja de Ingenieros',
  'Caja Forense',
  'CSP',
  'DASUTEN',
  'Doctored',
  'Ecles San Pedro',
  'Emerger',
  'Energía Salud',
  'Federación Médica',
  'Federada Salud',
  'Galeno',
  'Grupo San Nicolás',
  'IAPOS',
  'Integral Salud',
  'IOMA',
  'IOSFA',
  'Jerárquicos Salud',
  'LPF',
  'Luis Pasteur',
  'Medifé',
  'Mutuales Sistema ASOR',
  'Mutualyf',
  'Omint',
  'Osam',
  'Osce',
  'OSECAC',
  'OSDE',
  'Osemm',
  'Ospa',
  'Ospac',
  'Ospacarp / Ospatrones',
  'Ospat',
  'Ospatca',
  'Ospida',
  'Ospil',
  'OSPM (Mosaístas)',
  'Osprotura',
  'OSSEG Adherente',
  'OSSEG Básico, Salud, Especial e Int',
  'OSSEG Cone Beam',
  'OSSEG Integral',
  'OSSEG Prótesis Integral',
  'PAMI',
  'Poder Judicial',
  'Policía Federal',
  'Prensa',
  'Prevención Salud',
  'Provincia ART',
  'SADAIC',
  'Sancor Salud',
  'Sistema ASOR',
  'Sistema ASOR: Planes 100 Especial y Primario',
  'Swiss Medical',
  'UPCN',
  'William Hope'
];

export const ALL_INSURANCES = OBRAS_SOCIALES_LIST;
